apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo
  namespace: default
spec:
  # replicas: 10
  selector:
    matchLabels:
      app: rancher-demo
  template:
    metadata:
      labels:
        app: rancher-demo
    spec:
      containers:
        - name: rancher-demo
          image: bashofmann/rancher-demo:1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          env:
            - name: COW_COLOR
              value: purple
            - name: REFRESH_INTERVAL
              value: "10"
          readinessProbe:
            httpGet:
              port: web
              path: /
