apiVersion: v1
kind: Service
metadata:
  name: rancher-demo
  namespace: default
spec:
  type: NodePort
  selector:
    app: rancher-demo
  ports:
  - name: web
    nodePort: 30002
    port: 8080
    targetPort: web